### ISSUE TITLE
Mirrored Pedestal Crash

### ISSUE THREAD

**Issue by ZeekDaGeek** [SamsTheNerd/HexGloop#30]
v0.1.0 Forge

Attempting to place a Media Phial in the Mirrored Pedestal cashes a crash, them damned NULLs are everywhere:

<details>
<summary>
Crash report
</summary>

```
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2023-11-19 16:29:41
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because the return value of "com.samsthenerd.hexgloop.blockentities.BlockEntityPedestal.getPersistentUUID()" is null
	at net.minecraft.world.entity.Entity.getNoMoving(Entity.java:12850) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinEntity,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:EntityAccessor,pl:mixin:APP:botania_xplat.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:corgilib.mixins.json:MixinEntity,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:hexgloop-common.mixins.json:lightning.MixinProtectItems,pl:mixin:APP:hexgloop-common.mixins.json:mirroritems.MixinItemsNoMoving,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:ars_nouveau.mixins.json:light.LightEntityMixin,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:mediaworks-common.mixins.json:projection.EntityMixin,pl:mixin:APP:hexerei.mixin.json:light.HexereiLightEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.collision_based_landing_pos.MixinEntity,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.observers_see_entities.MixinEntity,pl:mixin:APP:fabrication.mixins.json:j_pedantry.entities_cant_climb.MixinEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.splash_on_inanimates.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_equip_sound.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.entities_sink_in_falling_fluids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.velocity_based_fall_damage_reset.MixinLivingEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_sneak_bypass.MixinEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.enhanced_moistness.MixinEntity,pl:mixin:APP:fabrication.mixins.json:i_woina.no_swim.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.mob_ids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.killmessage.MixinEntity,pl:mixin:A}
	at net.minecraft.world.entity.Entity.handler$dja000$noMove(Entity.java:12870) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinEntity,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:EntityAccessor,pl:mixin:APP:botania_xplat.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:corgilib.mixins.json:MixinEntity,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:hexgloop-common.mixins.json:lightning.MixinProtectItems,pl:mixin:APP:hexgloop-common.mixins.json:mirroritems.MixinItemsNoMoving,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:ars_nouveau.mixins.json:light.LightEntityMixin,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:mediaworks-common.mixins.json:projection.EntityMixin,pl:mixin:APP:hexerei.mixin.json:light.HexereiLightEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.collision_based_landing_pos.MixinEntity,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.observers_see_entities.MixinEntity,pl:mixin:APP:fabrication.mixins.json:j_pedantry.entities_cant_climb.MixinEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.splash_on_inanimates.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_equip_sound.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.entities_sink_in_falling_fluids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.velocity_based_fall_damage_reset.MixinLivingEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_sneak_bypass.MixinEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.enhanced_moistness.MixinEntity,pl:mixin:APP:fabrication.mixins.json:i_woina.no_swim.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.mob_ids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.killmessage.MixinEntity,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6478_(Entity.java) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:create.mixins.json:EntityMixin,pl:mixin:APP:kubejs-forge.mixins.json:EntityMixin,pl:mixin:APP:kubejs-common.mixins.json:EntityMixin,pl:mixin:APP:entitycollisionfpsfix.mixins.json:MixinEntity,pl:mixin:APP:ad_astra_giselle_addon.mixin.common.json:minecraft.EntityMixin,pl:mixin:APP:shrink.mixins.json:MixinEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:structure_gel.mixins.json:EntityMixin,pl:mixin:APP:botania_xplat.mixins.json:EntityAccessor,pl:mixin:APP:botania_xplat.mixins.json:EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:corgilib.mixins.json:MixinEntity,pl:mixin:APP:ad_astra-common.mixins.json:EntityInvoker,pl:mixin:APP:ad_astra-common.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:elementalcraft.mixins.json:MixinEntity,pl:mixin:APP:mixins.artifacts.json:item.aquadashers.EntityMixin,pl:mixin:APP:mixins.artifacts.json:item.umbrella.EntityMixin,pl:mixin:APP:hexgloop-common.mixins.json:lightning.MixinProtectItems,pl:mixin:APP:hexgloop-common.mixins.json:mirroritems.MixinItemsNoMoving,pl:mixin:APP:mixins.shetiphiancore.json:SPC_ThinBlockHandler$_Entity,pl:mixin:APP:curios.mixins.json:AccessorEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.EntityAccess,pl:mixin:APP:ars_nouveau.mixins.json:light.LightEntityMixin,pl:mixin:APP:entityculling.mixins.json:CullableMixin,pl:mixin:APP:mediaworks-common.mixins.json:projection.EntityMixin,pl:mixin:APP:hexerei.mixin.json:light.HexereiLightEntityMixin,pl:mixin:APP:netherportalfix.mixins.json:EntityAccessor,pl:mixin:APP:railways-common.mixins.json:conductor_possession.MixinEntity,pl:mixin:APP:railways-common.mixins.json:client.AccessorEntity,pl:mixin:APP:blueflame.mixin.json:MixinEntity,pl:mixin:APP:hexplat.mixins.json:accessor.AccessorEntity,pl:mixin:APP:quark.mixins.json:EntityMixin,pl:mixin:APP:expandability.mixins.json:swimming.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.EntityMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.EntityMixin,pl:mixin:APP:create.mixins.json:ContraptionDriverInteractMixin,pl:mixin:APP:create.mixins.json:client.EntityContraptionInteractionMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.collision_based_landing_pos.MixinEntity,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.observers_see_entities.MixinEntity,pl:mixin:APP:fabrication.mixins.json:j_pedantry.entities_cant_climb.MixinEntity,pl:mixin:APP:fabrication.mixins.json:z_combined.splash_on_inanimates.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.disable_equip_sound.MixinEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.entities_sink_in_falling_fluids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:f_balance.velocity_based_fall_damage_reset.MixinLivingEntity,pl:mixin:APP:fabrication.mixins.json:c_tweaks.no_sneak_bypass.MixinEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.enhanced_moistness.MixinEntity,pl:mixin:APP:fabrication.mixins.json:i_woina.no_swim.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.mob_ids.MixinEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.killmessage.MixinEntity,pl:mixin:A}
	at net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:129) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ItemEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:ItemEntityAccessor,pl:mixin:APP:botania_xplat.mixins.json:ItemEntityMixin,pl:mixin:APP:ae2.mixins.json:ItemEntityMixin,pl:mixin:APP:ad_astra-common.mixins.json:gravity.CommonGravityEntityMixin,pl:mixin:APP:spirit.common.mixins.json:ItemEntityMixin,pl:mixin:APP:silentgear.mixins.json:MixinItemEntity,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ItemEntityAccess,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ItemEntityAccess,pl:mixin:APP:dankstorage.mixins.json:ItemEntityMixin,pl:mixin:APP:getittogetherdrops.mixins.json:ItemEntityMixin,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.protection_on_any_item.MixinItemEntity,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.fire_protection_on_any_item.MixinItemEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.item_safe_cactus.MixinItemEntity,pl:mixin:APP:fabrication.mixins.json:i_woina.billboard_drops.MixinItemEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.despawning_items_blink.MixinItemEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.item_despawn.MixinItemEntity,pl:mixin:APP:ars_elemental.mixins.json:ItemEntityMixin,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:269) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:fabrication.mixins.json:c_tweaks.long_levelup_sound_at_30.MixinClientWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.void_fog_particles.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.Level.m_46653_(MixinLevel.java:457) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:utilitix.mixins.json:MixinLevel,pl:mixin:APP:observable.common.json:LevelMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinLevel,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.water_fills_on_break.MixinWorld,pl:mixin:A}
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:251) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:fabrication.mixins.json:c_tweaks.long_levelup_sound_at_30.MixinClientWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.void_fog_particles.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:classloading}
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:249) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:ClientLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ClientLevelMixin,pl:mixin:APP:rubidium.mixins.json:features.chunk_rendering.MixinClientWorld,pl:mixin:APP:rubidium.mixins.json:features.fast_biome_colors.MixinClientWorld,pl:mixin:APP:mixins.oculus.vertexformat.json:block_rendering.MixinClientLevel,pl:mixin:APP:flywheel.mixins.json:ClientLevelMixin,pl:mixin:APP:starlight.mixins.json:client.world.ClientLevelMixin,pl:mixin:APP:entityculling.mixins.json:ClientWorldMixin,pl:mixin:APP:byg.mixins.json:access.client.ClientLevelAccess,pl:mixin:APP:blue_skies.mixins.json:ClientLevelMixin,pl:mixin:APP:architectury.mixins.json:MixinClientLevel,pl:mixin:APP:hexplat.mixins.json:client.MixinClientLevel,pl:mixin:APP:fabrication.mixins.json:c_tweaks.long_levelup_sound_at_30.MixinClientWorld,pl:mixin:APP:fabrication.mixins.json:i_woina.void_fog_particles.MixinClientWorld,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1791) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1078) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:computing_frames,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23911!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.2.14.jar%23150!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23137!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc2.jar:mmc2] {}
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?] {}
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?] {}
```

</details>

**Comment by SamsTheNerd** [comment]
fixed for v0.1.1 !

**Comment by SamsTheNerd** [comment]
actually, gonna keep this open until the update is out so people can see it

**Comment by SamsTheNerd** [comment]
fix is out now !
